id: A242928BA
title: Prayer for the Long Life of Khyenrab Chökyi Özer
type: translation
pechas:
- I4839A34C
- I4E40494B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:56:30.139550
  last_modified_at: 2023-01-04 11:56:30.139564
  collections:
  - Gatön Ngawang Lekpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I4839A34C/84C3: E895
  I4E40494B/7111: E895
